# Generated by Django 2.0.5 on 2018-06-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('discount', models.FloatField(default=0)),
                ('discount_sum', models.FloatField(default=0)),
                ('total_sum', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('user_inn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('sum', models.FloatField()),
                ('check_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Check')),
            ],
        ),
    ]
