# Generated by Django 2.0.5 on 2018-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_qrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='total_sum',
            field=models.FloatField(),
        ),
    ]
